<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec.coffee</string>
	</array>
	<key>foldingStartMarker</key>
	<string>.*(-&gt;|=&gt;)\s*$|.*[\[{]\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*[}\]]\s*$</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Jasmine CoffeeScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.coffee</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.coffee.jasmine</string>
	<key>uuid</key>
	<string>488F5D65-2EA7-4D99-9BA9-0771C6E5535D</string>
</dict>
</plist>
